### PR TITLE
Ignore EOF-Error in validation

### PR DESCRIPTION
**Pull request by domano**

### CODE REVIEW

**Comment by domano** [comment]
https://github.com/xeipuuv/gojsonschema/issues/181

**Comment by johandorland** [comment]
As this error is only thrown when using the ReaderLoader I think it's more appropriate to catch the error in the `jsonIOLoader` that is creates. Instead of directly returning the decoded json just catch the error there and only pass it on upwards if it is not an `err.EOF` https://github.com/xeipuuv/gojsonschema/blob/master/jsonLoader.go#L315

Your solution will also work, but it feels a bit out of place.

**Comment by domano** [comment]
In my local version the line fixed the problem (the document was not nil, tested it).
I will create another PR shortly. Thanks for the quick reaction! :)

**Comment by domano** [comment]
You have to read the Reader which is returned before you can do the validation - error on my part.

**Pull request closed without merging**
