### PR TITLE
int64 max/min values tests added

### PR DESCRIPTION
**Pull request by frol-kr**
Addresses issue https://github.com/xeipuuv/gojsonschema/issues/192

### CODE REVIEW

**Comment by johandorland** [comment]
What is the thought behind adding a test without a fix? Now the test suite just fails.

**Comment by frol-kr** [comment]
I will make a fix with regard of big.Float
thank you for giving a reference on the pr (https://github.com/xeipuuv/gojsonschema/pull/172)

**Comment by frol-kr** [comment]
@johandorland, I think that you could have a look at pr at this point

**Comment by johandorland** [comment]
I still have some nit picks about the code and mainly it also doesn't allow for JSON big numbers as integers. I wrote my own PR in #194, so if you want you can take a look at that and then I'll merge that PR instead.

**Pull request merged**
